"""baseline: full katha schema

Revision ID: 3b50a73dae88
Revises: 
Create Date: 2026-07-19 09:31:04.184584

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b50a73dae88'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('families',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('keepers',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('family_id', sa.String(length=32), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('role', sa.Enum('OWNER', 'LISTENER', name='keeperrole'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('storytellers',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('family_id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('address_as', sa.String(length=120), nullable=False),
    sa.Column('phone_e164', sa.String(length=20), nullable=False),
    sa.Column('language', sa.String(length=16), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('tts_voice', sa.String(length=64), nullable=False),
    sa.Column('consent', sa.Enum('PENDING', 'GRANTED', 'DECLINED', 'REVOKED', name='consentstatus'), nullable=False),
    sa.Column('consented_at', sa.DateTime(), nullable=True),
    sa.Column('keeper_notes', sa.Text(), nullable=False),
    sa.Column('next_call_at', sa.DateTime(), nullable=True),
    sa.Column('cadence_days', sa.Integer(), nullable=False),
    sa.Column('life_brief', sa.Text(), nullable=False),
    sa.Column('life_brief_version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('api_tokens',
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('keeper_id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['keeper_id'], ['keepers.id'], ),
    sa.PrimaryKeyConstraint('token')
    )
    op.create_table('call_sessions',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('storyteller_id', sa.String(length=32), nullable=False),
    sa.Column('status', sa.Enum('SCHEDULED', 'DIALING', 'IN_PROGRESS', 'COMPLETED', 'NO_ANSWER', 'DROPPED', 'FAILED', name='sessionstatus'), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=False),
    sa.Column('audio_key', sa.String(length=512), nullable=False),
    sa.Column('planned_themes', sa.JSON(), nullable=False),
    sa.Column('resumed_from_id', sa.String(length=32), nullable=True),
    sa.Column('life_brief_version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['resumed_from_id'], ['call_sessions.id'], ),
    sa.ForeignKeyConstraint(['storyteller_id'], ['storytellers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chapters',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('storyteller_id', sa.String(length=32), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('body', sa.JSON(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'VERIFIED', 'PUBLISHED', name='chapterstatus'), nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['storyteller_id'], ['storytellers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('storyteller_id', 'ordinal', 'version')
    )
    op.create_table('entities',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('storyteller_id', sa.String(length=32), nullable=False),
    sa.Column('kind', sa.Enum('PERSON', 'PLACE', 'EVENT', 'ERA', 'OBJECT', name='entitykind'), nullable=False),
    sa.Column('canonical_name', sa.String(length=200), nullable=False),
    sa.Column('aliases', sa.JSON(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('attrs', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['storyteller_id'], ['storytellers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('facts',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('storyteller_id', sa.String(length=32), nullable=False),
    sa.Column('entity_id', sa.String(length=32), nullable=True),
    sa.Column('statement', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('session_id', sa.String(length=32), nullable=False),
    sa.Column('segment_ids', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['call_sessions.id'], ),
    sa.ForeignKeyConstraint(['storyteller_id'], ['storytellers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('follow_ups',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('storyteller_id', sa.String(length=32), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('source_session_id', sa.String(length=32), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ASKED', 'RETIRED', name='followupstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['source_session_id'], ['call_sessions.id'], ),
    sa.ForeignKeyConstraint(['storyteller_id'], ['storytellers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transcript_segments',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('session_id', sa.String(length=32), nullable=False),
    sa.Column('idx', sa.Integer(), nullable=False),
    sa.Column('speaker', sa.Enum('STORYTELLER', 'BIOGRAPHER', name='speaker'), nullable=False),
    sa.Column('t_start_ms', sa.Integer(), nullable=False),
    sa.Column('t_end_ms', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('language', sa.String(length=16), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['call_sessions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'idx')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transcript_segments')
    op.drop_table('follow_ups')
    op.drop_table('facts')
    op.drop_table('entities')
    op.drop_table('chapters')
    op.drop_table('call_sessions')
    op.drop_table('api_tokens')
    op.drop_table('storytellers')
    op.drop_table('keepers')
    op.drop_table('families')
    # ### end Alembic commands ###
