"""chapter source session

Revision ID: a5086fd3911d
Revises: 450d02c22d44
Create Date: 2026-07-19 21:25:20.033234

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a5086fd3911d'
down_revision: Union[str, Sequence[str], None] = '450d02c22d44'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chapters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source_session_id', sa.String(length=32), nullable=True))
        batch_op.create_foreign_key(None, 'call_sessions', ['source_session_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chapters', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('source_session_id')

    # ### end Alembic commands ###
